// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using POSLayer.Context;


#nullable disable

namespace POSLayer.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260328230357_entitytypeschanged")]
    partial class entitytypeschanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POSLayer.Models.Bonus", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Barrier0")
                        .HasColumnType("int");

                    b.Property<int>("Barrier1")
                        .HasColumnType("int");

                    b.Property<int>("Barrier10")
                        .HasColumnType("int");

                    b.Property<int>("Barrier11")
                        .HasColumnType("int");

                    b.Property<int>("Barrier12")
                        .HasColumnType("int");

                    b.Property<int>("Barrier13")
                        .HasColumnType("int");

                    b.Property<int>("Barrier14")
                        .HasColumnType("int");

                    b.Property<int>("Barrier15")
                        .HasColumnType("int");

                    b.Property<int>("Barrier16")
                        .HasColumnType("int");

                    b.Property<int>("Barrier17")
                        .HasColumnType("int");

                    b.Property<int>("Barrier18")
                        .HasColumnType("int");

                    b.Property<int>("Barrier19")
                        .HasColumnType("int");

                    b.Property<int>("Barrier2")
                        .HasColumnType("int");

                    b.Property<int>("Barrier20")
                        .HasColumnType("int");

                    b.Property<int>("Barrier3")
                        .HasColumnType("int");

                    b.Property<int>("Barrier4")
                        .HasColumnType("int");

                    b.Property<int>("Barrier5")
                        .HasColumnType("int");

                    b.Property<int>("Barrier6")
                        .HasColumnType("int");

                    b.Property<int>("Barrier7")
                        .HasColumnType("int");

                    b.Property<int>("Barrier8")
                        .HasColumnType("int");

                    b.Property<int>("Barrier9")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("BonusHiddenEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BonusHiddenStartTime")
                        .HasColumnType("time");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<int>("DaysAvailable")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<double>("HalfStepValue")
                        .HasColumnType("float");

                    b.Property<string>("PlanDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<double>("StepValue")
                        .HasColumnType("float");

                    b.HasKey("IID");

                    b.ToTable("Bonus");
                });

            modelBuilder.Entity("POSLayer.Models.Category", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BgColour")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("DistributionIID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FSize")
                        .HasColumnType("float");

                    b.Property<string>("FStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FgColour")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("MenuIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("IID");

                    b.HasIndex("DistributionIID");

                    b.HasIndex("MenuIID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("POSLayer.Models.CategoryItem", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableFor")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BgColor")
                        .HasColumnType("int");

                    b.Property<int>("ButtonType")
                        .HasColumnType("int");

                    b.Property<string>("CategoryIID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Compulsary")
                        .HasColumnType("int");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<double>("DPrice")
                        .HasColumnType("float");

                    b.Property<double>("DTax")
                        .HasColumnType("float");

                    b.Property<string>("DistributionIID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FSize")
                        .HasColumnType("float");

                    b.Property<string>("FStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FgColor")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PadFlag")
                        .HasColumnType("int");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.Property<double>("SaleTax")
                        .HasColumnType("float");

                    b.Property<double>("SitinPrice")
                        .HasColumnType("float");

                    b.Property<double>("SitinTax")
                        .HasColumnType("float");

                    b.Property<double>("TaPrice")
                        .HasColumnType("float");

                    b.Property<double>("TaTax")
                        .HasColumnType("float");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<bool>("WithImage")
                        .HasColumnType("bit");

                    b.HasKey("IID");

                    b.HasIndex("CategoryIID");

                    b.HasIndex("DistributionIID");

                    b.ToTable("CategoryItems");
                });

            modelBuilder.Entity("POSLayer.Models.Customer", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("POSLayer.Models.Debug", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DebugNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IID");

                    b.ToTable("Debugs");
                });

            modelBuilder.Entity("POSLayer.Models.Distribution", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("DistributionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IID");

                    b.HasIndex("MenuIID");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("POSLayer.Models.DistributionPrinter", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("DistributionIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrinterIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IID");

                    b.HasIndex("DistributionIID");

                    b.HasIndex("PrinterIID");

                    b.ToTable("DistributionPrinters", (string)null);
                });

            modelBuilder.Entity("POSLayer.Models.Employee", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<bool>("Shortable")
                        .HasColumnType("bit");

                    b.HasKey("IID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("POSLayer.Models.GenericImage", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<byte[]>("DisplayImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ExtraText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceIID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("POSLayer.Models.KitchenOrder", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("BeingModified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CompletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("OrderIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IID");

                    b.ToTable("KitchenOrders");
                });

            modelBuilder.Entity("POSLayer.Models.KitchenOrderItem", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("DistributionIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityButtonIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KitchenOrderIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IID");

                    b.HasIndex("KitchenOrderIID");

                    b.ToTable("KitchenOrderItems");
                });

            modelBuilder.Entity("POSLayer.Models.LogItem", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderItemText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.ToTable("LogItems");
                });

            modelBuilder.Entity("POSLayer.Models.Order", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Covers")
                        .HasColumnType("int");

                    b.Property<string>("CustomerIID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockedClientIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MoneyPaid")
                        .HasColumnType("float");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("Payment")
                        .HasColumnType("int");

                    b.Property<string>("PaymentFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ServiceChargeRate")
                        .HasColumnType("float");

                    b.Property<double>("ServiceChargeTaxRate")
                        .HasColumnType("float");

                    b.Property<string>("SessionIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Waiter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.HasIndex("CustomerIID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("POSLayer.Models.OrderItem", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CompletedQuantity")
                        .HasColumnType("float");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("DistributionIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityButtonIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityDisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("EntityIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("OrderGroupIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderItemText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("TaxPercent")
                        .HasColumnType("float");

                    b.HasKey("IID");

                    b.HasIndex("OrderIID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("POSLayer.Models.Printer", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AdminOnly")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<bool>("DeliveryPrinter")
                        .HasColumnType("bit");

                    b.Property<string>("LocalTerminal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrinterType")
                        .HasColumnType("int");

                    b.Property<int>("PrinterVisibility")
                        .HasColumnType("int");

                    b.Property<bool>("TakeAwayPrinter")
                        .HasColumnType("bit");

                    b.HasKey("IID");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("POSLayer.Models.Session", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CardTotal")
                        .HasColumnType("float");

                    b.Property<double>("CashTotal")
                        .HasColumnType("float");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("GrossSessionTotal")
                        .HasColumnType("float");

                    b.Property<double>("OnlineTotal")
                        .HasColumnType("float");

                    b.Property<double>("Peny1")
                        .HasColumnType("float");

                    b.Property<double>("Peny10")
                        .HasColumnType("float");

                    b.Property<double>("Peny2")
                        .HasColumnType("float");

                    b.Property<double>("Peny20")
                        .HasColumnType("float");

                    b.Property<double>("Peny5")
                        .HasColumnType("float");

                    b.Property<double>("Peny50")
                        .HasColumnType("float");

                    b.Property<double>("Pound1")
                        .HasColumnType("float");

                    b.Property<double>("Pound10")
                        .HasColumnType("float");

                    b.Property<double>("Pound100")
                        .HasColumnType("float");

                    b.Property<double>("Pound1000")
                        .HasColumnType("float");

                    b.Property<double>("Pound2")
                        .HasColumnType("float");

                    b.Property<double>("Pound20")
                        .HasColumnType("float");

                    b.Property<double>("Pound200")
                        .HasColumnType("float");

                    b.Property<double>("Pound5")
                        .HasColumnType("float");

                    b.Property<double>("Pound50")
                        .HasColumnType("float");

                    b.Property<double>("Pound500")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("X1total")
                        .HasColumnType("float");

                    b.Property<double>("X2total")
                        .HasColumnType("float");

                    b.Property<double>("X3total")
                        .HasColumnType("float");

                    b.HasKey("IID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("POSLayer.Models.Shop", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentSessionIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<double>("DefaultTaxRate")
                        .HasColumnType("float");

                    b.Property<string>("KitchenFooter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KitchenHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KitchenModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdersEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptFooter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportFooter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ServiceChargeRate")
                        .HasColumnType("float");

                    b.Property<double>("ServiceChargeTaxRate")
                        .HasColumnType("float");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpAccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpEmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpFromLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoidText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("POSLayer.Models.StockItem", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Conversion")
                        .HasColumnType("int");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("QuantityType")
                        .HasColumnType("int");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UsedQuantity")
                        .HasColumnType("float");

                    b.HasKey("IID");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("POSLayer.Models.Supplier", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Whatsup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("POSLayer.Models.Table", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentOrderIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("LockedClientIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("ParentTableIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("TableCovers")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableType")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("XLocation")
                        .HasColumnType("int");

                    b.Property<int>("YLocation")
                        .HasColumnType("int");

                    b.HasKey("IID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("POSLayer.Models.TableGroup", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("IID");

                    b.ToTable("TableGroups");
                });

            modelBuilder.Entity("POSLayer.Models.TheMenu", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("POSLayer.Models.User", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("POSLayer.Models.XOrder", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Covers")
                        .HasColumnType("int");

                    b.Property<string>("CustomerIID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockedClientIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MoneyPaid")
                        .HasColumnType("float");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("Payment")
                        .HasColumnType("int");

                    b.Property<string>("PaymentFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ServiceChargeRate")
                        .HasColumnType("float");

                    b.Property<double>("ServiceChargeTaxRate")
                        .HasColumnType("float");

                    b.Property<string>("SessionIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Waiter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IID");

                    b.HasIndex("CustomerIID");

                    b.ToTable("Xorders");
                });

            modelBuilder.Entity("POSLayer.Models.XOrderItem", b =>
                {
                    b.Property<string>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CompletedQuantity")
                        .HasColumnType("float");

                    b.Property<int>("DOrder")
                        .HasColumnType("int");

                    b.Property<string>("DistributionIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityButtonIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityDisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("EntityIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("OrderGroupIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderIID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderItemText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("TaxPercent")
                        .HasColumnType("float");

                    b.HasKey("IID");

                    b.HasIndex("OrderIID");

                    b.ToTable("XorderItems");
                });

            modelBuilder.Entity("POSLayer.Models.Category", b =>
                {
                    b.HasOne("POSLayer.Models.Distribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionIID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POSLayer.Models.TheMenu", "Menu")
                        .WithMany("categories")
                        .HasForeignKey("MenuIID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Distribution");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("POSLayer.Models.CategoryItem", b =>
                {
                    b.HasOne("POSLayer.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryIID");

                    b.HasOne("POSLayer.Models.Distribution", "Distribution")
                        .WithMany()
                        .HasForeignKey("DistributionIID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Distribution");
                });

            modelBuilder.Entity("POSLayer.Models.Distribution", b =>
                {
                    b.HasOne("POSLayer.Models.TheMenu", "Menu")
                        .WithMany("distributions")
                        .HasForeignKey("MenuIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("POSLayer.Models.DistributionPrinter", b =>
                {
                    b.HasOne("POSLayer.Models.Distribution", "Distribution")
                        .WithMany("DistributionPrinters")
                        .HasForeignKey("DistributionIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POSLayer.Models.Printer", "Printer")
                        .WithMany("DistributionPrinters")
                        .HasForeignKey("PrinterIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribution");

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("POSLayer.Models.KitchenOrderItem", b =>
                {
                    b.HasOne("POSLayer.Models.KitchenOrder", null)
                        .WithMany("items")
                        .HasForeignKey("KitchenOrderIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("POSLayer.Models.Order", b =>
                {
                    b.HasOne("POSLayer.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerIID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("POSLayer.Models.OrderItem", b =>
                {
                    b.HasOne("POSLayer.Models.Order", "Order")
                        .WithMany("items")
                        .HasForeignKey("OrderIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("POSLayer.Models.XOrder", b =>
                {
                    b.HasOne("POSLayer.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerIID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("POSLayer.Models.XOrderItem", b =>
                {
                    b.HasOne("POSLayer.Models.XOrder", "Order")
                        .WithMany("items")
                        .HasForeignKey("OrderIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("POSLayer.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("POSLayer.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("POSLayer.Models.Distribution", b =>
                {
                    b.Navigation("DistributionPrinters");
                });

            modelBuilder.Entity("POSLayer.Models.KitchenOrder", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("POSLayer.Models.Order", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("POSLayer.Models.Printer", b =>
                {
                    b.Navigation("DistributionPrinters");
                });

            modelBuilder.Entity("POSLayer.Models.TheMenu", b =>
                {
                    b.Navigation("categories");

                    b.Navigation("distributions");
                });

            modelBuilder.Entity("POSLayer.Models.XOrder", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
