//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace DTRMMobilePadSL.DTRMNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DTRMNS.ISimpleBusinessService")]
    public interface ISimpleBusinessService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISimpleBusinessService/EnsureBSLayer", ReplyAction="http://tempuri.org/ISimpleBusinessService/EnsureBSLayerResponse")]
        System.IAsyncResult BeginEnsureBSLayer(System.AsyncCallback callback, object asyncState);
        
        void EndEnsureBSLayer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISimpleBusinessService/GetCategoryList", ReplyAction="http://tempuri.org/ISimpleBusinessService/GetCategoryListResponse")]
        System.IAsyncResult BeginGetCategoryList(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetCategoryList(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleBusinessServiceChannel : DTRMMobilePadSL.DTRMNS.ISimpleBusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCategoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCategoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleBusinessServiceClient : System.ServiceModel.ClientBase<DTRMMobilePadSL.DTRMNS.ISimpleBusinessService>, DTRMMobilePadSL.DTRMNS.ISimpleBusinessService {
        
        private BeginOperationDelegate onBeginEnsureBSLayerDelegate;
        
        private EndOperationDelegate onEndEnsureBSLayerDelegate;
        
        private System.Threading.SendOrPostCallback onEnsureBSLayerCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCategoryListDelegate;
        
        private EndOperationDelegate onEndGetCategoryListDelegate;
        
        private System.Threading.SendOrPostCallback onGetCategoryListCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SimpleBusinessServiceClient() {
        }
        
        public SimpleBusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleBusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleBusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleBusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EnsureBSLayerCompleted;
        
        public event System.EventHandler<GetCategoryListCompletedEventArgs> GetCategoryListCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DTRMMobilePadSL.DTRMNS.ISimpleBusinessService.BeginEnsureBSLayer(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnsureBSLayer(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void DTRMMobilePadSL.DTRMNS.ISimpleBusinessService.EndEnsureBSLayer(System.IAsyncResult result) {
            base.Channel.EndEnsureBSLayer(result);
        }
        
        private System.IAsyncResult OnBeginEnsureBSLayer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DTRMMobilePadSL.DTRMNS.ISimpleBusinessService)(this)).BeginEnsureBSLayer(callback, asyncState);
        }
        
        private object[] OnEndEnsureBSLayer(System.IAsyncResult result) {
            ((DTRMMobilePadSL.DTRMNS.ISimpleBusinessService)(this)).EndEnsureBSLayer(result);
            return null;
        }
        
        private void OnEnsureBSLayerCompleted(object state) {
            if ((this.EnsureBSLayerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnsureBSLayerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnsureBSLayerAsync() {
            this.EnsureBSLayerAsync(null);
        }
        
        public void EnsureBSLayerAsync(object userState) {
            if ((this.onBeginEnsureBSLayerDelegate == null)) {
                this.onBeginEnsureBSLayerDelegate = new BeginOperationDelegate(this.OnBeginEnsureBSLayer);
            }
            if ((this.onEndEnsureBSLayerDelegate == null)) {
                this.onEndEnsureBSLayerDelegate = new EndOperationDelegate(this.OnEndEnsureBSLayer);
            }
            if ((this.onEnsureBSLayerCompletedDelegate == null)) {
                this.onEnsureBSLayerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnsureBSLayerCompleted);
            }
            base.InvokeAsync(this.onBeginEnsureBSLayerDelegate, null, this.onEndEnsureBSLayerDelegate, this.onEnsureBSLayerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DTRMMobilePadSL.DTRMNS.ISimpleBusinessService.BeginGetCategoryList(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCategoryList(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> DTRMMobilePadSL.DTRMNS.ISimpleBusinessService.EndGetCategoryList(System.IAsyncResult result) {
            return base.Channel.EndGetCategoryList(result);
        }
        
        private System.IAsyncResult OnBeginGetCategoryList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DTRMMobilePadSL.DTRMNS.ISimpleBusinessService)(this)).BeginGetCategoryList(callback, asyncState);
        }
        
        private object[] OnEndGetCategoryList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((DTRMMobilePadSL.DTRMNS.ISimpleBusinessService)(this)).EndGetCategoryList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCategoryListCompleted(object state) {
            if ((this.GetCategoryListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCategoryListCompleted(this, new GetCategoryListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCategoryListAsync() {
            this.GetCategoryListAsync(null);
        }
        
        public void GetCategoryListAsync(object userState) {
            if ((this.onBeginGetCategoryListDelegate == null)) {
                this.onBeginGetCategoryListDelegate = new BeginOperationDelegate(this.OnBeginGetCategoryList);
            }
            if ((this.onEndGetCategoryListDelegate == null)) {
                this.onEndGetCategoryListDelegate = new EndOperationDelegate(this.OnEndGetCategoryList);
            }
            if ((this.onGetCategoryListCompletedDelegate == null)) {
                this.onGetCategoryListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCategoryListCompleted);
            }
            base.InvokeAsync(this.onBeginGetCategoryListDelegate, null, this.onEndGetCategoryListDelegate, this.onGetCategoryListCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override DTRMMobilePadSL.DTRMNS.ISimpleBusinessService CreateChannel() {
            return new SimpleBusinessServiceClientChannel(this);
        }
        
        private class SimpleBusinessServiceClientChannel : ChannelBase<DTRMMobilePadSL.DTRMNS.ISimpleBusinessService>, DTRMMobilePadSL.DTRMNS.ISimpleBusinessService {
            
            public SimpleBusinessServiceClientChannel(System.ServiceModel.ClientBase<DTRMMobilePadSL.DTRMNS.ISimpleBusinessService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginEnsureBSLayer(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("EnsureBSLayer", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEnsureBSLayer(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EnsureBSLayer", _args, result);
            }
            
            public System.IAsyncResult BeginGetCategoryList(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCategoryList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetCategoryList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetCategoryList", _args, result)));
                return _result;
            }
        }
    }
}
